### ISSUE TITLE
Sound_samples does not implement volume control.

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#1022]
introduced in #1017
