### ISSUE TITLE
Strict Aliasing error on MinGW

### ISSUE THREAD

**Issue by The-Renaissance** [tsoding/nothing#1008]
Hi Alexey, 
I was trying to build on MinGW with GCC 6.3 when I got the following errors:
1. the compiler doesn't seem to recognize the %z scanf flag and triggers the format warning
2. in /level/level_editor/color_picker.c at 111:5:
```C
static void color_picker_revert(void *layer, Context context)
{
    trace_assert(layer);
    ColorPicker *color_picker = layer;
    log_info("color_picker_revert\n");
    *color_picker = create_color_picker_from_rgba(*((Color *)context.data));
}
```
The compiler doesn't like converting from a void* to a ColorPicker* and triggers the strict-aliasing warning: 
```
c:/Users/Lenovo/Desktop/nothing/src/game/level/level_editor/color_picker.c: In function 'color_picker_revert':
c:/Users/Lenovo/Desktop/nothing/src/game/level/level_editor/color_picker.c:111:5: error: dereferencing type-punned point
er will break strict-aliasing rules [-Werror=strict-aliasing]
     *color_picker = create_color_picker_from_rgba(*((Color *)context.data));
```
#875

**Comment by The-Renaissance** [comment]
#875

**Comment by The-Renaissance** [comment]
Related Twitch Clip: https://www.twitch.tv/tsoding/clip/SpeedyKindPandaPeteZarollTie
Not following type safety breaks MinGW build somehow

**Comment by The-Renaissance** [comment]
MinGW build is SUCCESSFUL
![图片](https://user-images.githubusercontent.com/25717879/62735330-f1b96d80-b9f8-11e9-837d-c0b95376c5f9.png)
@rexim to fix the strict-alias issue I defined -fno-strict-aliasing, is that OK for you?

**Comment by The-Renaissance** [comment]
See #1009 pull request @rexim

**Comment by rexim** [comment]
Resolved by #1009
